### ISSUE TITLE
Fetching no data at all

### ISSUE THREAD

**Issue by elpeter25** [jsrozner/google_drive_auditer#1]
Hi,

I'm running googdrivecheck.py with python 3.7 and it always parse nothing.

Parsed 0 files   0 folders

Is still working?

**Comment by jsrozner** [comment]
It should be working, though I haven't played / tested/ worked on it in a few months. Did you update your config file? Sometimes getting the API to play right can be the hardest part.

**Comment by jsrozner** [comment]
Hey so I realized that one of the defaults in googdrivecheck.py was to run with a single example file. I changed that flag to be False, so that it should now query your whole google drive. You should be able to git pull again and run. I also updated README with some comments about setup. But if you were already getting parsed 0 files and 0 folders then your setup (auth, etc) is probably correct. Lemme know if this fixes it for you!

**Comment by elpeter25** [comment]
Thanks so much!! It worked and I've been able to retrieve data from my drive, it's not working with a shared drive though. Is it possible to make it work with a shared drive?

Thanks in advance for this great job!

**Comment by elpeter25** [comment]
BTW to make pydrive work with Shared Drives I had to modify files.py a bit:

```
diff files.py files.py.bak27012020
63,67d62
<     # Teamdrive support
< ##    self['corpus'] = 'DEFAULT'
< ##    self['supportsAllDrives'] = True
< ##    self['includeItemsFromAllDrives'] = True
<
70d64
<
241,246c235,237
<         metadata = self.auth.service.files().get(
<           fileId=file_id,
<           fields=fields,
<           # Teamdrive support
<           supportsAllDrives=True
<         ).execute(http=self.http)
---
>         metadata = self.auth.service.files().get(fileId=file_id,
>                                                  fields=fields)\
>           .execute(http=self.http)
374,377d364
<
<     # teamdrive support
<     param['supportsAllDrives'] = True
<
400,403d386
<
<     # Teamdrive support
<     param['supportsAllDrives'] = True
<
425,428d407
<
<     # Teamdrive support
<     param['supportsAllDrives'] = True
<
451,454d429
<
<     # Teamdrive support
<     param['supportsAllDrives'] = True
<
475,478d449
<
<     # Teamdrive support
<     param['supportsAllDrives'] = True
<
504,507d474
<
<     # Teamdrive support
<     param['supportsAllDrives'] = True
<
```

Just in case you were wondering...

**Comment by jsrozner** [comment]
Cool. I can add a note to the readme for shared drive support, and you could also try a pull request to the pydrive folks: add a flag for them /  modify some constructor (I haven't looked carefully) with the tweaks you listed so that they support querying all files? 

(I tried them previously to ask if they could provide some sort of safety wrapper for any API changes and they said that they'd be happy to accept a pull request if I wrote it)
